version: "3.8"
services:
  url-shortener:
    build: .
    container_name: url-shortener
    restart: unless-stopped
    ports:
      - "8082:8082"
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
